CREATE DATABASE IF NOT EXISTS hevenh3nz;
USE hevenh3nz;
CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gamertag VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE posts ADD COLUMN featured BOOLEAN DEFAULT FALSE;
